In [1]:
import pandas as pd

In [2]:
hiv = pd.read_csv('2014_Kenya_s_HIV_AIDS_profile_data_by_County.csv')
hiv.head() # first 5

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
0,BARINGO,3%,707,34,53%,9194,632588,2.9%,3.2%,34%,...,4498,2406,952,345,11249,5512,2241,525,73,"(0.669251980315, 35.946465352700)"
1,BOMET,5.8%,1875,89,38%,24389,824347,4.5%,8.7%,35%,...,11930,4511,2525,407,16664,8165,2865,1393,195,"(-0.726294583441, 35.298597586700)"
2,BUNGOMA,3.2%,83,93,64%,26093,1750634,2.4%,6%,38%,...,17164,10982,3578,1140,30493,14942,5426,864,249,"(0.749285239620, 34.640460875600)"
3,BUSIA,6.8%,51,57,183%,16065,523875,5.6%,13.9%,39%,...,10588,19398,2207,1657,27068,13263,6767,533,153,"(0.387443677554, 34.193631488400)"
4,ELEGEYO-MARAKWET,2.5%,400,19,38%,5208,421282,5%,1.5%,38%,...,2542,978,538,89,6287,3081,1412,297,42,"(0.802219000000, 35.536563000000)"

In [3]:
hiv.shape # number of counties (rows)

(47, 24)

In [4]:
hiv.columns

Index([u'COUNTY NAME', u'Adult (15+) HIV prevalence', u'New Hiv Infections (Adults 15+)', u'New Hiv Infections (Children 0-14)', u'ART Coverage', u'HIV+ Adults', u'Total Population', u'Hiv Prevalence (men)', u'Hiv Prevalence (women)', u'POE-Prevention of mother-to-child transmission', u'POE-voluntering and testing', u'POE-Tuberculosis', u'POE-Medical ward', u'POE-Overral', u'Adults in need of ART', u'Adults receiving ART', u'Children in need of ART', u'Children receiving ART', u'No.of households with an  orphan', u'poor households with an orphan', u'(KES) cash transfer beneficiary poor households with an orphan', u'Aids related Deaths (15+)', u'Aids related Deaths (0-14)', u'Coordinates'], dtype='object')

In [5]:
# summary statistics i.e the mean, count, max, std
hiv.describe()

,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),HIV+ Adults,Total Population,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14)
count,47.000000,47.000000,47.000000,46.000000,47.000000,47.000000,47.000000,47.000000,47.000000,47.000000,47.000000,46.000000,47.000000
mean,1885.787234,272.914894,28633.659574,904730.695652,16189.000000,12621.829787,3020.489362,1279.595745,23036.361702,11288.382979,3236.191489,1041.913043,221.297872
std,2737.390879,618.337456,32458.014449,607135.901102,20101.898206,17977.657189,3448.942068,1729.226412,16031.193645,7856.704873,1872.204950,904.849449,271.640180
min,18.000000,2.000000,307.000000,115520.000000,250.000000,66.000000,114.000000,5.000000,2380.000000,1166.000000,557.000000,50.000000,9.000000
25%,365.000000,27.500000,9078.500000,550590.750000,4449.000000,2654.500000,911.500000,243.000000,10868.500000,5325.500000,1917.500000,414.500000,66.000000
50%,988.000000,60.000000,18923.000000,856303.000000,10586.000000,6507.000000,2058.000000,725.000000,18492.000000,9061.000000,2474.000000,747.500000,132.000000
75%,1898.000000,94.000000,27892.000000,1057656.000000,16619.000000,12585.500000,2997.000000,1544.500000,29242.500000,14329.000000,4637.500000,1378.250000,203.000000
max,12279.000000,2700.000000,140629.000000,3781394.000000,102103.000000,93714.000000,15235.000000,6988.000000,69730.000000,34168.000000,8107.000000,3579.000000,1234.000000

In [6]:
# sort by number of new infection (children 0 -14) and get the top 5 counties
hiv.sort(columns='New Hiv Infections (Children 0-14)').tail()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
15,KISII,8%,4891,1075,48%,55970,1259489,4%,6.8%,52%,...,28214,13629,6068,1169,37838,18541,5089,1352,492,"(-0.774603757212, 34.774722983500)"
26,MIGORI,14.7%,6786,1492,89%,77650,1002499,10%,15.9%,32%,...,39147,34927,8419,3136,44951,22026,6135,1876,682,"(-0.989536843706, 34.363345307600)"
37,SIAYA,23.7%,9869,2170,82%,112962,920671,15.9%,23.3%,44%,...,56932,46413,12244,5285,54323,26618,6249,2728,992,"(-0.062129888622, 34.247641704500)"
16,KISUMU,19.3%,10349,2276,104%,118538,1059053,14.2%,20.5%,41%,...,59703,62280,12840,6881,56795,27830,6331,2861,1040,"(-0.169458694764, 34.835203466000)"
7,HOMA BAY,25.7%,12279,2700,70%,140629,1053465,17.8%,29.1%,38%,...,70837,46738,15235,6331,60958,29896,8107,3395,1234,"(-0.542809394155, 34.358996868700)"

In [7]:
# sort by number of new infections (Adults 15+) and get the top 5 counties
hiv.sort(columns='New Hiv Infections (Adults 15+)').tail()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
15,KISII,8%,4891,1075,48%,55970,1259489,4%,6.8%,52%,...,28214,13629,6068,1169,37838,18541,5089,1352,492,"(-0.774603757212, 34.774722983500)"
26,MIGORI,14.7%,6786,1492,89%,77650,1002499,10%,15.9%,32%,...,39147,34927,8419,3136,44951,22026,6135,1876,682,"(-0.989536843706, 34.363345307600)"
37,SIAYA,23.7%,9869,2170,82%,112962,920671,15.9%,23.3%,44%,...,56932,46413,12244,5285,54323,26618,6249,2728,992,"(-0.062129888622, 34.247641704500)"
16,KISUMU,19.3%,10349,2276,104%,118538,1059053,14.2%,20.5%,41%,...,59703,62280,12840,6881,56795,27830,6331,2861,1040,"(-0.169458694764, 34.835203466000)"
7,HOMA BAY,25.7%,12279,2700,70%,140629,1053465,17.8%,29.1%,38%,...,70837,46738,15235,6331,60958,29896,8107,3395,1234,"(-0.542809394155, 34.358996868700)"

In [8]:
# then number of new infections listing of top counties seem to be in the same order
# Does this mean the number of new adult and children infections are in the same order of in each county
hiv.sort(columns='New Hiv Infections (Adults 15+)').head()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
45,WAJIR,0.2%,18,2,26%,307,434524,0.1%,0%,38%,...,250,66,114,5,9707,4756,1649,79,10,"(1.808137623800, 40.034985639600)"
44,VIHIGA,3.8%,31,35,97%,9853,595301,2.7%,11.8%,38%,...,6511,6324,1357,769,19628,9618,3956,328,94,"(0.076265795868, 34.722323036100)"
39,TANA RIVER,1%,40,4,97%,1161,273205,1.9%,1.5%,38%,...,682,660,121,31,5789,2837,2033,50,9,"(-1.526366604320, 39.417869202900)"
20,LAMU,2.3%,44,5,95%,1263,115520,1.4%,3.2%,39%,...,739,700,131,80,2380,1166,557,NaN,10,"(-2.078682543640, 40.882860682000)"
3,BUSIA,6.8%,51,57,183%,16065,523875,5.6%,13.9%,39%,...,10588,19398,2207,1657,27068,13263,6767,533,153,"(0.387443677554, 34.193631488400)"

In [9]:
hiv.sort(columns='New Hiv Infections (Children 0-14)').head()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
45,WAJIR,0.2%,18,2,26%,307,434524,0.1%,0%,38%,...,250,66,114,5,9707,4756,1649,79,10,"(1.808137623800, 40.034985639600)"
39,TANA RIVER,1%,40,4,97%,1161,273205,1.9%,1.5%,38%,...,682,660,121,31,5789,2837,2033,50,9,"(-1.526366604320, 39.417869202900)"
24,MARSABIT,1.2%,81,4,86%,1480,306471,7%,1.6%,29%,...,866,746,163,93,8844,4333,1930,100,10,"(2.978658786520, 37.569536108800)"
20,LAMU,2.3%,44,5,95%,1263,115520,1.4%,3.2%,39%,...,739,700,131,80,2380,1166,557,NaN,10,"(-2.078682543640, 40.882860682000)"
8,ISIOLO,4.2%,151,8,60%,2822,150817,2.3%,5.7%,34%,...,1616,969,605,92,4323,2118,2437,95,18,"(1.010443077530, 38.542153120600)"

In [10]:
# where do we need to focus more on preventing mother to child infections?
hiv.sort(columns='POE-Prevention of mother-to-child transmission').tail()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
15,KISII,8%,4891,1075,48%,55970,1259489,4%,6.8%,52%,...,28214,13629,6068,1169,37838,18541,5089,1352,492,"(-0.774603757212, 34.774722983500)"
32,NAROK,5%,1806,86,38%,23504,968390,12.5%,6.3%,52%,...,11490,4351,2432,296,18021,8830,3058,1341,188,"(-1.254790332110, 35.576329213900)"
12,KIAMBU,3.8%,2931,95,102%,42425,1760692,2.3%,6.7%,53%,...,23747,24104,3041,2011,41068,20123,2906,1207,180,"(-1.068706065980, 36.823564257900)"
19,LAIKIPIA,3.7%,692,33,54%,8963,454412,3.2%,5.3%,85%,...,4400,2391,931,161,10488,5139,1718,514,72,"(0.323604122500, 36.771727858800)"
36,SAMBURU,5%,461,22,24%,6001,254997,2.3%,5.5%,99%,...,2934,700,621,55,7757,3801,2197,200,50,"(1.316854626050, 37.118394067000)"

In [11]:
hiv.loc[:, ['COUNTY NAME', 'Adults receiving ART', 'Adults in need of ART', 'Aids related Deaths (15+)']]

,COUNTY NAME,Adults receiving ART,Adults in need of ART,Aids related Deaths (15+)
0,BARINGO,2406,4498,525
1,BOMET,4511,11930,1393
2,BUNGOMA,10982,17164,864
3,BUSIA,19398,10588,533
4,ELEGEYO-MARAKWET,978,2542,297
5,EMBU,5130,5540,326
6,GARISSA,786,1649,521
7,HOMA BAY,46738,70837,3395
8,ISIOLO,969,1616,95
9,KAJIADO,5219,9827,1147
10,KAKAMEGA,21014,31896,1605
11,KERICHO,9299,7725,902
12,KIAMBU,24104,23747,1207
13,KILIFI,9884,13868,1021
14,KIRINYAGA,5831,6441,327
15,KISII,13629,28214,1352
16,KISUMU,62280,59703,2861
17,KITUI,9273,10561,622
18,KWALE,3227,10515,744
19,LAIKIPIA,2391,4400,514
20,LAMU,700,739,NaN
21,MACHAKOS,11542,15640,921
22,MAKUENI,9705,12754,751
23,MANDERA,77,1948,615
24,MARSABIT,746,866,100
25,MERU,9615,11658,686
26,MIGORI,34927,39147,1876
27,MOMBASA,26490,27168,2000
28,MURANG'A,7177,16074,817
29,NAIROBI,93714,102103,3579
30,NAKURU,16345,26255,3065
31,NANDI,6507,7969,930
32,NAROK,4351,11490,1341
33,NYAMIRA,6886,11840,567
34,NYANDARUA,5596,7281,370
35,NYERI,10471,10586,538
36,SAMBURU,700,2934,200
37,SIAYA,46413,56932,2728
38,TAITA TAVETA,2903,5570,410
39,TANA RIVER,660,682,50
40,THARAKA - NITHI,4177,4386,258
41,TRANS NZOIA,6618,11881,1387
42,TURKANA,3791,19068,2226
43,UASIN GISHU,17614,12223,1427
44,VIHIGA,6324,6511,328
45,WAJIR,66,250,79
46,WEST POKOT,1062,3667,428

In [12]:
# Do we have counties where the prevalence of HIV in women is 0%
hiv[hiv['Hiv Prevalence (women)'] == '0%']

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
45,WAJIR,0.2%,18,2,26%,307,434524,0.1%,0%,38%,...,250,66,114,5,9707,4756,1649,79,10,"(1.808137623800, 40.034985639600)"

In [13]:
# Whats the data on Mombasa county?
hiv[hiv['COUNTY NAME'] == 'MOMBASA']

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
27,MOMBASA,7.4%,1609,169,98%,47751,1068307,4.5%,10.5%,35%,...,27168,26490,4817,1995,21546,10557,1905,2000,351,"(-4.021256219730, 39.650882702600)"

In [14]:
# ART among adults highest in which county?
hiv.sort(columns='Adults receiving ART').tail()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
26,MIGORI,14.7%,6786,1492,89%,77650,1002499,10%,15.9%,32%,...,39147,34927,8419,3136,44951,22026,6135,1876,682,"(-0.989536843706, 34.363345307600)"
37,SIAYA,23.7%,9869,2170,82%,112962,920671,15.9%,23.3%,44%,...,56932,46413,12244,5285,54323,26618,6249,2728,992,"(-0.062129888622, 34.247641704500)"
7,HOMA BAY,25.7%,12279,2700,70%,140629,1053465,17.8%,29.1%,38%,...,70837,46738,15235,6331,60958,29896,8107,3395,1234,"(-0.542809394155, 34.358996868700)"
16,KISUMU,19.3%,10349,2276,104%,118538,1059053,14.2%,20.5%,41%,...,59703,62280,12840,6881,56795,27830,6331,2861,1040,"(-0.169458694764, 34.835203466000)"
29,NAIROBI,6.8%,3098,313,92%,102828,3781394,5.9%,9.7%,39%,...,102103,93714,9398,6988,69730,34168,2534,3579,448,"(-1.293413470280, 36.868189268200)"

In [15]:
# ART among children highest in which county?
hiv.sort(columns='Children receiving ART').tail()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
26,MIGORI,14.7%,6786,1492,89%,77650,1002499,10%,15.9%,32%,...,39147,34927,8419,3136,44951,22026,6135,1876,682,"(-0.989536843706, 34.363345307600)"
37,SIAYA,23.7%,9869,2170,82%,112962,920671,15.9%,23.3%,44%,...,56932,46413,12244,5285,54323,26618,6249,2728,992,"(-0.062129888622, 34.247641704500)"
7,HOMA BAY,25.7%,12279,2700,70%,140629,1053465,17.8%,29.1%,38%,...,70837,46738,15235,6331,60958,29896,8107,3395,1234,"(-0.542809394155, 34.358996868700)"
16,KISUMU,19.3%,10349,2276,104%,118538,1059053,14.2%,20.5%,41%,...,59703,62280,12840,6881,56795,27830,6331,2861,1040,"(-0.169458694764, 34.835203466000)"
29,NAIROBI,6.8%,3098,313,92%,102828,3781394,5.9%,9.7%,39%,...,102103,93714,9398,6988,69730,34168,2534,3579,448,"(-1.293413470280, 36.868189268200)"

In [16]:
hiv.sort(columns='Children receiving ART').head()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
45,WAJIR,0.2%,18,2,26%,307,434524,0.1%,0%,38%,...,250,66,114,5,9707,4756,1649,79,10,"(1.808137623800, 40.034985639600)"
23,MANDERA,1.7%,137,17,4%,3928,1025756,2%,2.3%,31%,...,1948,77,892,27,13208,6472,1650,615,81,"(3.436469488030, 40.738810166700)"
39,TANA RIVER,1%,40,4,97%,1161,273205,1.9%,1.5%,38%,...,682,660,121,31,5789,2837,2033,50,9,"(-1.526366604320, 39.417869202900)"
36,SAMBURU,5%,461,22,24%,6001,254997,2.3%,5.5%,99%,...,2934,700,621,55,7757,3801,2197,200,50,"(1.316854626050, 37.118394067000)"
6,GARISSA,2.1%,116,14,48%,3262,NaN,4.5%,0.7%,38%,...,1649,786,755,73,8532,4181,1687,521,69,"(-0.488910344831, 40.199278537800)"

In [17]:
hiv.sort(columns='Adults receiving ART').head()

,COUNTY NAME,Adult (15+) HIV prevalence,New Hiv Infections (Adults 15+),New Hiv Infections (Children 0-14),ART Coverage,HIV+ Adults,Total Population,Hiv Prevalence (men),Hiv Prevalence (women),POE-Prevention of mother-to-child transmission,...,Adults in need of ART,Adults receiving ART,Children in need of ART,Children receiving ART,No.of households with an orphan,poor households with an orphan,(KES) cash transfer beneficiary poor households with an orphan,Aids related Deaths (15+),Aids related Deaths (0-14),Coordinates
45,WAJIR,0.2%,18,2,26%,307,434524,0.1%,0%,38%,...,250,66,114,5,9707,4756,1649,79,10,"(1.808137623800, 40.034985639600)"
23,MANDERA,1.7%,137,17,4%,3928,1025756,2%,2.3%,31%,...,1948,77,892,27,13208,6472,1650,615,81,"(3.436469488030, 40.738810166700)"
39,TANA RIVER,1%,40,4,97%,1161,273205,1.9%,1.5%,38%,...,682,660,121,31,5789,2837,2033,50,9,"(-1.526366604320, 39.417869202900)"
36,SAMBURU,5%,461,22,24%,6001,254997,2.3%,5.5%,99%,...,2934,700,621,55,7757,3801,2197,200,50,"(1.316854626050, 37.118394067000)"
20,LAMU,2.3%,44,5,95%,1263,115520,1.4%,3.2%,39%,...,739,700,131,80,2380,1166,557,NaN,10,"(-2.078682543640, 40.882860682000)"